### ISSUE TITLE
Camera Scan just work in debug build

### ISSUE THREAD

**Issue by jo3ght** [pdliuw/ai_barcode#35]
Camera widget disappeared when i build release but it work on debug mode !
Log:
`E/flutter (25999): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, java.lang.NoSuchMethodException: c.d.c.e.values [], null, java.lang.RuntimeException: java.lang.NoSuchMethodException: c.d.c.e.values []
E/flutter (25999):      at java.lang.Enum.enumValues(Enum.java:270)
E/flutter (25999):      at java.lang.Enum.access$000(Enum.java:61)
E/flutter (25999):      at java.lang.Enum$1.create(Enum.java:277)
E/flutter (25999):      at java.lang.Enum$1.create(Enum.java:275)
E/flutter (25999):      at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
E/flutter (25999):      at java.lang.Enum.getSharedConstants(Enum.java:289)
E/flutter (25999):      at java.lang.Class.getEnumConstantsShared(Class.java:2459)
E/flutter (25999):      at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
E/flutter (25999):      at java.util.EnumMap.<init>(EnumMap.java:138)
E/flutter (25999):      at g.a.a.b.c.<init>(:1)
E/flutter (25999):      at c.a.a.d.<init>(Unknown Source:15)
E/flutter (25999):      at c.a.a.e.a(Unknown Source:9)
E/flutter (25999):      at io.flutter.plugin.platform.SingleViewPresentation.onCreate(Unknown Source:116)
E/flutter (25999):      at android.app.Dialog.dispatchOnCreate(Dialog.java:424)
E/flutter (25999):      at android.app.Dialog.show(Dialog.java:318)
E/flutter (25999):      at android.app.Presentation.show(Presentation.java:279)
E/flutter (25999):      at io.flutter.plugin.platform.y.<init>(Unknown Source:55)
E/flutter (25999):      at io.flutter.plugin.platform.y.a(Unknown Source:65)
E/flutter (25999):      at io.flutter.plugin.platform.m.g(Unknown Source:110)
E/flutter (25999):      at io.flutter.embedding.engine.p.D.i(:12)
E/flutter (25999):      at e.a.d.a.w.a(Unknown Source:17)
E/flutter (25999):      at io.flutter.embedding.engine.l.f.d(Unknown Source:25)
E/flutter (25999):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter (25999):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (25999):      at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (25999):      at android.os.Looper.loopOnce(Looper.java:161)
E/flutter (25999):      at android.os.Looper.loop(Looper.java:288)
E/flutter (25999):      at android.app.ActivityThread.main(ActivityThread.java:7829)
E/flutter (25999):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (25999):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (25999):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982)
E/flutter (25999): Caused by: java.lang.NoSuchMethodException: c.d.c.e.values []
E/flutter (25999):      at java.lang.Class.getMethod(Class.java:2103)
E/flutter (25999):      at java.lang.Class.getDeclaredMethod(Class.java:2081)
E/flutter (25999):      at java.lang.Enum.enumValues(Enum.java:267)
E/flutter (25999):      ... 30 more
E/flutter (25999): )
E/flutter (25999): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
E/flutter (25999): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter (25999): <asynchronous suspension>
E/flutter (25999): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1043)
E/flutter (25999): <asynchronous suspension>
E/flutter (25999): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:748)
E/flutter (25999): <asynchronous suspension>
E/flutter (25999): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:193)
E/flutter (25999): <asynchronous suspension>
E/flutter (25999): 
`

**Comment by kuntash34** [comment]
Thanks for great package,
But I am surprised how the package has been test, I have been using this package for several month and finally when I release I get to see big crash in my application. I don't think this is enhancement
@pdliuw Hope fully you will release fixed version sooner.

**Comment by CodingWithTashi** [comment]
This is due to missing proguard file.    
Create  proguard file(proguard-rules.pro) in your app directory (which is build.gradle app location) and add   
```
-keepclassmembers enum * {
	public static **[] values();
	public static ** valueOf(java.lang.String);
}
```

Then Update build.gradle file as below and you are good to go.   

```
 buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
 ```   
for more check this [link](https://github.com/serso/android-checkout/issues/138)

**Comment by wladrbarbosa** [comment]
This worked for me. Thanks.

> This is due to missing proguard file. Create proguard file(proguard-rules.pro) in your app directory (which is build.gradle app location) and add
> 
> ```
> -keepclassmembers enum * {
> 	public static **[] values();
> 	public static ** valueOf(java.lang.String);
> }
> ```
> 
> Then Update build.gradle file as below and you are good to go.
> 
> ```
>  buildTypes {
>         release {
>             minifyEnabled true
>             proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
>         }
>     }
> ```
> 
> for more check this [link](https://github.com/serso/android-checkout/issues/138)
